### ISSUE TITLE
Minor problem with weird build numbers

### ISSUE THREAD

**Issue by s0hvaperuna** [AnimeNeko/Atarashii#483]
I have a custom rom in my phone and atarashii doesn't like my build version "◄║JellySNAP ROM|Ξ|JSRAK47|Ξ|v7.0║►". I could change my build name for the time being but it could be good if you filter some of the characters out that cause problems like this character ◄. Here's the line that was causing problems from MALApi.java.
`private static final String USER_AGENT = "Atarashii! (Linux; Android " + Build.VERSION.RELEASE + "; " + Build.MODEL + " Build/" + Build.DISPLAY + ") " + okUa;`

**Comment by ratan12** [comment]
Ehm yeah.

Why do they make such versions... :/
I will have to discuss this first.

**Comment by ratan12** [comment]
Okay I searched a bit online and found this:
http://developer.android.com/reference/android/os/Build.VERSION.html#RELEASE

The user-visible version string. E.g., "1.0" or "3.4b5".
in your case "◄║JellySNAP ROM|Ξ|JSRAK47|Ξ|v7.0║►".
That entirely different!

I am afraid I can't do anything about this because this is the **worst build version** I have seen in my entire life XD

The other developer also doesn't know how we could fix this in a proper way.
So unless the developer of your ROM knows a way to fix this we are stuck with this.
Sorry.
