### ISSUE TITLE
Open links in app 

### ISSUE THREAD

**Issue by laserswift** [AnimeNeko/Atarashii#491]
So let's say you click on a manga or anime suggestion on a reddit app, instead of it opening in the browser, is it possible to have all http://myanimelist.net/* links open in the app?

If one makes it their default, of course. 

(By the way, thanks so much for providing a Floss flavor!)

**Comment by ratan12** [comment]
I forgot to comment on this issue...

Yes, it is possible and I have mentioned it once in an issue : https://github.com/AnimeNeko/Atarashii/issues/178
Apparently 2 years ago.

With which URLs do you want to see the app opening (if you could choose only a few) and why?
http://myanimelist.net/anime/?
http://myanimelist.net/manga/?

Depending on your answer I will set the milestone.

**Comment by laserstrike** [comment]
Well, I visit the anime (reddit.com/r/anime) and manga (reddit.com/r/manga) subreddits a lot, and there's always a post or a thread or a comment with anime and manga suggestions that can range from one or two at a time--to dozens. Since they have their own bots that change those suggestions into links, it'd be nice if those links can be opened directly in the app instead of having to type each anime's or manga's name when searching for it. Also, MAL sends out emails when new anime or manga are added to their site, with links to each one. I guess there are others who visit these subreddits and/or get these emails who would like this functionality. 

Of course, it would just be for anime and manga. No need to open to specific forums posts in MAL as I barely see any links to that anywhere.

I'm not sure how it would work -- is it coded so that all links that meet "http://myanimelist.net/manga/" and "http://myanimelist.net/anime/" requirement then initiates an automatic search in the app according to what comes after? Or does the MAL api automatically index the url for you? (Total noob, I apologize.)

**Comment by Efreak** [comment]
I would say also add links to /search, /profile, and any other pages that may get implemented (/people, /characters, /features, /news, /forums that I can think of off the top of my head). Basically, it would be nice to be able to use the app to view any pages that the app *can* view. Just don't make it *all* pages on myanimelist.net, or you'll get issues (forkhub tries to intercept links to github project wikis, but can't display them)

**Comment by ratan12** [comment]
Yes, I won't try to put all pages in atarashii. I put this on the roadmap
