### ISSUE TITLE
More search filtering

### ISSUE THREAD

**Issue by Efreak** [AnimeNeko/Atarashii#495]
Can you add filters to the Browse page to search by contributor, and by type?

Contributor: I'd like to be able to search for anime by publisher/studio (ghilbi, NHK, etc) and for mangas by a certain author. Ideally this information should also be displayed in the main page of the detail view as well (#494).

Type: It should be possible to further narrow down searches beyond manga/anime to OVA/TV/Movie/etc fir anime and Manga/Manwha/Novel/etc for print.

Also, the publishing status should either have a n/a entry (search regardless of publication status) or the ability to select more than one option from it. I keep going through search results lately, and not finding anything because the publication status is set incorrectly.

**Comment by ratan12** [comment]
**Can you add filters to the Browse page to search by contributor, and by type?**
We are using https://myanimelist.net/anime.php for this part and does not contain that info I think.
What do you mean with type?

**I'd like to be able to search for anime by publisher/studio**
That is possible but I was way too lazy to add all those names manually. I will do it soon.

**Type: It should be possible to further narrow down searches beyond manga/anime to OVA/TV/Movie/etc fir anime and Manga/Manwha/Novel/etc for print.**
That does already exist.

**Also, the publishing status should either have a n/a entry**
I was working on it.

**Comment by srvrguy** [comment]
Rather than add manually, we could see about an API endpoint to fetch the latest Publisher list, as it's likely to change.

**Comment by Efreak** [comment]
> Can you add filters to the Browse page to search by contributor, and by type?
> We are using https://myanimelist.net/anime.php for this part and does not contain that info I think.

How about a way to search [people.php](https://myanimelist.net/people.php?q=name) instead? MAL is a bit odd/lacking in this; I can search most other book websites for a title+author combination (public library, amazon, goodreads, etc)

**Comment by srvrguy** [comment]
Maybe. This is an API-level issue, not an application one, though. That means it may take a bit longer to get implemented, if at all.

Basically, in order to use MAL in a somewhat sane way, we have a separate piece of code that runs on a server that acts like a web browser to MAL and returns information in a format that the application can use. Basically, we move the intensive part of interpreting ever-changing HTML pages to a central point that can be updated quickly when needed. MAL is very quirky, so having this helps standardize how the application works and takes away a lot of code and complexity that would drain mobile batteries.

You can put in a request for this extra search feature over at the [API site](https://bitbucket.org/ratan12/atarashii-api), or I can do so if you would rather not.

**Comment by Efreak** [comment]
[Done](https://bitbucket.org/ratan12/atarashii-api/issues/128/request-person-search-view)
